version: '3.1'
services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: snippetbox
